version: '3'
services:
  app:
    #build:
      #context: .
      #args:
        #- enable_mecab=1
    image: harumaki2000/ai-chifuyu:latest
    platform: linux/amd64
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - './config.json:/ai/config.json:ro'
      - './font.ttf:/ai/font.ttf:ro'
      - './data:/ai/data'
    restart: always
